// One-time (re-runnable) resolver for player headshots. The slow/rate-limited part of TheSportsDB is the
// SEARCH api (name -> image URL), not serving the image. So we resolve every squad player's cutout URL ONCE
// here and vendor the map to lib/data/playerImages.ts; at runtime it's a plain lookup (no API call, no limit).
// The browser still loads the image from TheSportsDB's CDN (free, reliable) — like the Wikimedia stadium photos.
//
// Resumable: it reads the existing vendored map and skips players already resolved (or recorded as "no photo"),
// so you can re-run after a rate-limit interruption. Polite to the free key: serial, delayed, backs off on 429.
//
//   bun run scripts/fetch-player-images.ts
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { TEAM_BY_ESPN } from "@/lib/data/teams";

const KEY = process.env.THESPORTSDB_KEY || "3";
const API = "https://www.thesportsdb.com/api/v1/json";
const TEAMS_LIST = "https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/teams";
const ROSTER = (id: string) => `https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/teams/${id}/roster`;
const OUT = "lib/data/playerImages.ts";

const norm = (s: string) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().trim();
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

interface TSDBPlayer { strNationality?: string; strCutout?: string; strThumb?: string }

// Load existing map (resume). Stored value: a URL string, or "" recorded as a confirmed "no photo".
function loadExisting(): Record<string, string> {
  if (!existsSync(OUT)) return {};
  const m = readFileSync(OUT, "utf8").match(/\{[\s\S]*\}/);
  try {
    return m ? (JSON.parse(m[0]) as Record<string, string>) : {};
  } catch {
    return {};
  }
}

function write(map: Record<string, string>) {
  const sorted = Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));
  const hdr =
    "// AUTO-GENERATED by scripts/fetch-player-images.ts — resolved TheSportsDB headshot URLs keyed by\n" +
    '// "teamCode|playerName". "" means "checked, no photo". Re-run the script to refresh. Do not hand-edit.\n' +
    "export const PLAYER_IMAGES: Record<string, string> = ";
  writeFileSync(OUT, hdr + JSON.stringify(sorted, null, 0) + ";\n");
}

async function getJSON(url: string): Promise<unknown | null> {
  for (let attempt = 0; attempt < 6; attempt++) {
    try {
      const r = await fetch(url, { headers: { "User-Agent": "WC2026Predictions/1.0" } });
      if (r.status === 429 || r.status >= 500) {
        const wait = 4000 * (attempt + 1);
        process.stdout.write(` (429, backing off ${wait / 1000}s)`);
        await sleep(wait);
        continue;
      }
      if (!r.ok) return null;
      return await r.json();
    } catch {
      await sleep(3000);
    }
  }
  return null;
}

async function resolve(name: string, country: string): Promise<string | null | undefined> {
  const d = (await getJSON(`${API}/${KEY}/searchplayers.php?p=${encodeURIComponent(name)}`)) as { player?: TSDBPlayer[] } | null;
  if (d === null) return undefined; // transient — leave unresolved so a re-run retries
  const cn = norm(country);
  const same = (d.player ?? []).filter((p) => p.strNationality && norm(p.strNationality) === cn);
  const pick = same.find((p) => p.strCutout) ?? same.find((p) => p.strThumb) ?? null;
  return pick?.strCutout || pick?.strThumb || null;
}

// ── run ──
const map = loadExisting();
console.log(`loaded ${Object.keys(map).length} existing entries`);

const list = (await getJSON(TEAMS_LIST)) as { sports?: { leagues?: { teams?: { team?: { id?: string; displayName?: string } }[] }[] }[] } | null;
const teams = (list?.sports?.[0]?.leagues?.[0]?.teams ?? [])
  .map((t) => ({ id: t.team?.id, code: t.team?.displayName ? TEAM_BY_ESPN[t.team.displayName]?.code : undefined, name: t.team?.displayName }))
  .filter((t): t is { id: string; code: string; name: string } => !!t.id && !!t.code && !!t.name);
console.log(`teams: ${teams.length}`);

let resolved = 0, missing = 0, skipped = 0, sinceWrite = 0;
for (const team of teams) {
  const country = TEAM_BY_ESPN[team.name] ? team.name : team.name; // ESPN displayName === our team.name
  const roster = (await getJSON(ROSTER(team.id))) as { athletes?: { displayName?: string; items?: { displayName?: string }[] }[] } | null;
  const names: string[] = [];
  for (const a of roster?.athletes ?? []) {
    if (a.items?.length) for (const it of a.items) it.displayName && names.push(it.displayName);
    else if (a.displayName) names.push(a.displayName);
  }
  process.stdout.write(`\n${team.code} (${names.length}): `);
  for (const name of names) {
    const k = `${team.code}|${name}`;
    if (k in map) { skipped++; continue; }
    const url = await resolve(name, country);
    if (url === undefined) { process.stdout.write("?"); continue; } // transient — retry on a later run
    map[k] = url ?? "";
    if (url) { resolved++; process.stdout.write("."); } else { missing++; process.stdout.write("x"); }
    if (++sinceWrite >= 20) { write(map); sinceWrite = 0; }
    await sleep(350); // be gentle on the free key
  }
}
write(map);
console.log(`\n\ndone — resolved ${resolved}, no-photo ${missing}, skipped(existing) ${skipped}, total ${Object.keys(map).length}`);
